apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-capstone
  labels:
    app: uda-capstone
spec:
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: uda-capstone
  replicas: 3
  template:
    metadata:
      labels:
        app: uda-capstone
    spec:
      containers:
      - name: uda-capstone
        image: abhishekraghav08/uda-capstone:uda-capstone
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080