apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-capstone
  labels:
    app: uda-capstone
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: uda-capstone
  strategy:
    rollingUpdate:
      #maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uda-capstone
    spec:
      containers:
      - name: uda-capstone
        image: abhishekraghav08/uda-capstone:uda-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: uda-capstone
  labels:
      app: uda-capstone
spec:
  type: LoadBalancer
  selector:
    app: my-capstone
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP